### ISSUE TITLE
Course 3 Preparation, Double HTML Escape Characters

### ISSUE THREAD

**Issue by amnn** [code61/short_format_notes#5]
In the "homebrew_mac" section, the code blocks inside the exercise sections have been escaped twice (i.e. escaped once to replace `<` with `&gt;` but then replaced once again to get `&amp;gt;`, etc).

This is just a hunch, but the sections that this seems to happen to have been indented with two tabs,
whereas other sections are indented with spaces, so I don't know whether that has anything to do with this behaviour.

**Comment by tomclose** [comment]
I don't think that's the issue (I changed to spaces and it didn't help). I've left the [notes](http://notes.code61.org/c3prep/#!2_homebrew_mac) without the code blocks but also without the double-indenting.

This unexpected double-indenting is a problem throughout the notes. It's on my list of things to look into when I get a chance, but I don't really have the bandwidth at the moment :(.

**Comment by amnn** [comment]
No worries! Thanks for the quick fix, it should be enough for now.
